// <auto-generated />
using System;
using Gms.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gms.Api.Migrations
{
    [DbContext(typeof(GmsDbContext))]
    [Migration("20260707092049_InitialChangeDomain")]
    partial class InitialChangeDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gms.Api.Domain.AppEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Environments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666601"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "DEV",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Status = "Active",
                            Type = "Geliştirme"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666602"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TEST",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Status = "Active",
                            Type = "Test"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666603"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "UAT",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Status = "Active",
                            Type = "Kullanıcı Kabul"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666604"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PROD",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Status = "Active",
                            Type = "Üretim"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666611"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "DEV",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Status = "Active",
                            Type = "Geliştirme"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666612"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TEST",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Status = "Active",
                            Type = "Test"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666613"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "UAT",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Status = "Active",
                            Type = "Kullanıcı Kabul"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666614"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PROD",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Status = "Active",
                            Type = "Üretim"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "requester@gms.local",
                            FullName = "Requester User",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "architect@gms.local",
                            FullName = "Architect User",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "executor@gms.local",
                            FullName = "Executor User",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "qa@gms.local",
                            FullName = "QA Specialist",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gms.local",
                            FullName = "System Administrator",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.ChangeAffectedAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ChangeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId");

                    b.ToTable("ChangeAffectedAssets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31110001-0000-0000-0000-000000000001"),
                            AssetName = "Operatör Arayüzü",
                            AssetType = "Application",
                            ChangeRequestId = new Guid("11110001-0000-0000-0000-000000000001"),
                            Criticality = "High",
                            Description = "Operatör web uygulaması."
                        },
                        new
                        {
                            Id = new Guid("31110002-0000-0000-0000-000000000002"),
                            AssetName = "EBR Üretim Veritabanı",
                            AssetType = "Database",
                            ChangeRequestId = new Guid("11110002-0000-0000-0000-000000000002"),
                            Criticality = "Critical",
                            Description = "Birincil üretim veritabanı."
                        },
                        new
                        {
                            Id = new Guid("31110003-0000-0000-0000-000000000003"),
                            AssetName = "batch_record Tablosu",
                            AssetType = "Table",
                            ChangeRequestId = new Guid("11110003-0000-0000-0000-000000000003"),
                            Criticality = "High",
                            Description = "Parti kayıt tablosu."
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.ChangeAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ChangeAuditEvents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51110001-0000-0000-0000-000000000001"),
                            ActorUserId = new Guid("b2222222-2222-2222-2222-222222222201"),
                            ChangeRequestId = new Guid("11110001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Değişiklik oluşturuldu.",
                            EventType = "ChangeCreated"
                        },
                        new
                        {
                            Id = new Guid("51110002-0000-0000-0000-000000000002"),
                            ActorUserId = new Guid("b2222222-2222-2222-2222-222222222205"),
                            ChangeRequestId = new Guid("11110002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Değişiklik oluşturuldu.",
                            EventType = "ChangeCreated"
                        },
                        new
                        {
                            Id = new Guid("51110003-0000-0000-0000-000000000003"),
                            ActorUserId = new Guid("b2222222-2222-2222-2222-222222222201"),
                            ChangeRequestId = new Guid("11110003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Değişiklik oluşturuldu.",
                            EventType = "ChangeCreated"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.ChangeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId");

                    b.ToTable("ChangeDocuments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41110001-0000-0000-0000-000000000001"),
                            ChangeRequestId = new Guid("11110001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentName = "UAT Test Kanıtı",
                            DocumentType = "TestEvidence",
                            Status = "Active",
                            Version = "v1"
                        },
                        new
                        {
                            Id = new Guid("41110002-0000-0000-0000-000000000002"),
                            ChangeRequestId = new Guid("11110002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentName = "Veri Düzeltme Betiği",
                            DocumentType = "SqlScript",
                            Status = "Active",
                            Version = "v1"
                        },
                        new
                        {
                            Id = new Guid("41110003-0000-0000-0000-000000000003"),
                            ChangeRequestId = new Guid("11110003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentName = "Şema Değişikliği Betiği",
                            DocumentType = "SqlScript",
                            Status = "Active",
                            Version = "v1"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.ChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ChangeClass")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ChangeNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PlannedImplementationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedRollbackDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChangeNo")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RiskLevel");

                    b.HasIndex("Status");

                    b.ToTable("ChangeRequests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11110001-0000-0000-0000-000000000001"),
                            BusinessReason = "Operatör verimliliğini artırmak için arayüz iyileştirmesi gereklidir.",
                            ChangeClass = "Normal",
                            ChangeNo = "CHG-2026-000001",
                            ChangeType = "ApplicationDeployment",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b2222222-2222-2222-2222-222222222201"),
                            CustomerId = new Guid("d4444444-4444-4444-4444-444444444401"),
                            Description = "Operatör ekranlarında kullanılabilirlik güncellemesi.",
                            EnvironmentId = new Guid("f6666666-6666-6666-6666-666666666604"),
                            PlannedImplementationDate = new DateTime(2026, 8, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Medium",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            RiskLevel = "Medium",
                            RiskScore = 45,
                            SourceReference = "JIRA-2001",
                            SourceSystem = "JIRA",
                            Status = "Draft",
                            Title = "Operatör arayüzü dağıtımı"
                        },
                        new
                        {
                            Id = new Guid("11110002-0000-0000-0000-000000000002"),
                            BusinessReason = "Yanlış durum bilgisi üretim raporlamasını bozuyor; acil düzeltme gerekli.",
                            ChangeClass = "Emergency",
                            ChangeNo = "CHG-2026-000002",
                            ChangeType = "SqlDataFix",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b2222222-2222-2222-2222-222222222205"),
                            CustomerId = new Guid("d4444444-4444-4444-4444-444444444401"),
                            Description = "Yanlış işaretlenmiş parti kayıtlarının acil düzeltmesi.",
                            EnvironmentId = new Guid("f6666666-6666-6666-6666-666666666604"),
                            PlannedImplementationDate = new DateTime(2026, 7, 20, 2, 0, 0, 0, DateTimeKind.Utc),
                            PlannedRollbackDate = new DateTime(2026, 7, 20, 4, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Critical",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            RiskLevel = "Critical",
                            RiskScore = 110,
                            SourceReference = "JIRA-2002",
                            SourceSystem = "JIRA",
                            Status = "Submitted",
                            Title = "Üretim veri düzeltmesi"
                        },
                        new
                        {
                            Id = new Guid("11110003-0000-0000-0000-000000000003"),
                            BusinessReason = "Denetim izlenebilirliği için inceleyen kullanıcı bilgisi tutulmalı.",
                            ChangeClass = "Normal",
                            ChangeNo = "CHG-2026-000003",
                            ChangeType = "DatabaseSchemaChange",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b2222222-2222-2222-2222-222222222201"),
                            CustomerId = new Guid("d4444444-4444-4444-4444-444444444401"),
                            Description = "batch_record tablosuna reviewed_by kolonu eklenecek.",
                            EnvironmentId = new Guid("f6666666-6666-6666-6666-666666666604"),
                            PlannedImplementationDate = new DateTime(2026, 7, 25, 2, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            RiskLevel = "High",
                            RiskScore = 75,
                            SourceReference = "JIRA-2003",
                            SourceSystem = "JIRA",
                            Status = "Draft",
                            Title = "Veritabanı şeması güncellemesi"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.ChangeRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeploymentInstructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ImplementationNotes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("int");

                    b.Property<string>("RollbackOwner")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RollbackScript")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollbackStrategy")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SqlScript")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId", "RevisionNo")
                        .IsUnique();

                    b.ToTable("ChangeRevisions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21110001-0000-0000-0000-000000000001"),
                            ChangeRequestId = new Guid("11110001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b2222222-2222-2222-2222-222222222201"),
                            DeploymentInstructions = "CI paketini PROD ortamına dağıt.",
                            EstimatedDurationMinutes = 30,
                            ImplementationNotes = "",
                            RevisionNo = 1,
                            RollbackOwner = "Ali Vural",
                            RollbackScript = "Önceki artifact sürümüne geri dön (v1.1).",
                            RollbackStrategy = "Artifact geri alma",
                            SqlScript = "",
                            TechnicalSummary = "Angular derlemesi PROD'a dağıtılacak."
                        },
                        new
                        {
                            Id = new Guid("21110002-0000-0000-0000-000000000002"),
                            ChangeRequestId = new Guid("11110002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b2222222-2222-2222-2222-222222222205"),
                            DeploymentInstructions = "",
                            EstimatedDurationMinutes = 20,
                            ImplementationNotes = "",
                            RevisionNo = 1,
                            RollbackOwner = "System Administrator",
                            RollbackScript = "UPDATE batch_record SET status='PENDING' WHERE status='REVIEWED' AND updated_today=1;",
                            RollbackStrategy = "Ters UPDATE + yedekten geri yükleme",
                            SqlScript = "UPDATE batch_record SET status='REVIEWED' WHERE status='PENDING';",
                            TechnicalSummary = "Parti durum düzeltmesi (UPDATE) uygulanacak."
                        },
                        new
                        {
                            Id = new Guid("21110003-0000-0000-0000-000000000003"),
                            ChangeRequestId = new Guid("11110003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b2222222-2222-2222-2222-222222222201"),
                            DeploymentInstructions = "",
                            EstimatedDurationMinutes = 45,
                            ImplementationNotes = "",
                            RevisionNo = 1,
                            RollbackOwner = "",
                            RollbackScript = "",
                            RollbackStrategy = "",
                            SqlScript = "ALTER TABLE batch_record ADD reviewed_by NVARCHAR(100) NULL;",
                            TechnicalSummary = "ALTER TABLE ile kolon eklenecek."
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444401"),
                            Code = "ABDI",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Abdi İbrahim",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444402"),
                            Code = "BILIM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bilim İlaç",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Code = "EBR-MIG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("d4444444-4444-4444-4444-444444444401"),
                            Description = "Elektronik Batch Record geçiş projesi.",
                            Name = "EBR Migration",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Code = "MES-UPG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("d4444444-4444-4444-4444-444444444402"),
                            Description = "MES sürüm yükseltme projesi.",
                            Name = "MES Upgrade",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Releases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07777777-7777-7777-7777-777777777701"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b2222222-2222-2222-2222-222222222205"),
                            Description = "EBR Migration üretim yayını.",
                            EnvironmentId = new Guid("f6666666-6666-6666-6666-666666666604"),
                            Name = "REL-2026-001",
                            PlannedDate = new DateTime(2026, 7, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Status = "Planned",
                            Version = "v1.0"
                        },
                        new
                        {
                            Id = new Guid("07777777-7777-7777-7777-777777777702"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b2222222-2222-2222-2222-222222222201"),
                            Description = "MES Upgrade UAT taslak yayını.",
                            EnvironmentId = new Guid("f6666666-6666-6666-6666-666666666613"),
                            Name = "REL-2026-002",
                            PlannedDate = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Status = "Draft",
                            Version = "v0.9"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111101"),
                            Description = "Değişiklik/sürüm talebi oluşturan kullanıcı.",
                            Name = "Requester"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111102"),
                            Description = "Teknik tasarım ve mimari değerlendirme yapan kullanıcı.",
                            Name = "Architect"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111103"),
                            Description = "Onaylanan değişiklikleri yürüten kullanıcı.",
                            Name = "Executor"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111104"),
                            Description = "Doğrulama ve kalite kontrol yapan kullanıcı.",
                            Name = "QA"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111105"),
                            Description = "Sistem yöneticisi — tüm yetkiler.",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("AppUserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333301"),
                            AppUserId = new Guid("b2222222-2222-2222-2222-222222222201"),
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333302"),
                            AppUserId = new Guid("b2222222-2222-2222-2222-222222222202"),
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333303"),
                            AppUserId = new Guid("b2222222-2222-2222-2222-222222222203"),
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111103")
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333304"),
                            AppUserId = new Guid("b2222222-2222-2222-2222-222222222204"),
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111104")
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333305"),
                            AppUserId = new Guid("b2222222-2222-2222-2222-222222222205"),
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111105")
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.AppEnvironment", b =>
                {
                    b.HasOne("Gms.Api.Domain.Project", "Project")
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gms.Api.Domain.ChangeAffectedAsset", b =>
                {
                    b.HasOne("Gms.Api.Domain.ChangeRequest", "ChangeRequest")
                        .WithMany("Assets")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeRequest");
                });

            modelBuilder.Entity("Gms.Api.Domain.ChangeAuditEvent", b =>
                {
                    b.HasOne("Gms.Api.Domain.ChangeRequest", "ChangeRequest")
                        .WithMany("AuditEvents")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeRequest");
                });

            modelBuilder.Entity("Gms.Api.Domain.ChangeDocument", b =>
                {
                    b.HasOne("Gms.Api.Domain.ChangeRequest", "ChangeRequest")
                        .WithMany("Documents")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeRequest");
                });

            modelBuilder.Entity("Gms.Api.Domain.ChangeRequest", b =>
                {
                    b.HasOne("Gms.Api.Domain.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gms.Api.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gms.Api.Domain.AppEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gms.Api.Domain.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Environment");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gms.Api.Domain.ChangeRevision", b =>
                {
                    b.HasOne("Gms.Api.Domain.ChangeRequest", "ChangeRequest")
                        .WithMany("Revisions")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeRequest");
                });

            modelBuilder.Entity("Gms.Api.Domain.Project", b =>
                {
                    b.HasOne("Gms.Api.Domain.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Gms.Api.Domain.Release", b =>
                {
                    b.HasOne("Gms.Api.Domain.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gms.Api.Domain.AppEnvironment", "Environment")
                        .WithMany("Releases")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gms.Api.Domain.Project", "Project")
                        .WithMany("Releases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Environment");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gms.Api.Domain.UserRole", b =>
                {
                    b.HasOne("Gms.Api.Domain.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gms.Api.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gms.Api.Domain.AppEnvironment", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Gms.Api.Domain.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Gms.Api.Domain.ChangeRequest", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("AuditEvents");

                    b.Navigation("Documents");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Gms.Api.Domain.Customer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Gms.Api.Domain.Project", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Gms.Api.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
