// <auto-generated />
using System;
using Gms.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gms.Api.Migrations
{
    [DbContext(typeof(GmsDbContext))]
    [Migration("20260706080232_InitialBusinessFoundation")]
    partial class InitialBusinessFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gms.Api.Domain.AppEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Environments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666601"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "DEV",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Status = "Active",
                            Type = "Geliştirme"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666602"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TEST",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Status = "Active",
                            Type = "Test"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666603"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "UAT",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Status = "Active",
                            Type = "Kullanıcı Kabul"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666604"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PROD",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Status = "Active",
                            Type = "Üretim"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666611"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "DEV",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Status = "Active",
                            Type = "Geliştirme"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666612"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TEST",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Status = "Active",
                            Type = "Test"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666613"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "UAT",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Status = "Active",
                            Type = "Kullanıcı Kabul"
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666614"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PROD",
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Status = "Active",
                            Type = "Üretim"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "requester@gms.local",
                            FullName = "Requester User",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "architect@gms.local",
                            FullName = "Architect User",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "executor@gms.local",
                            FullName = "Executor User",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "qa@gms.local",
                            FullName = "QA Specialist",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gms.local",
                            FullName = "System Administrator",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444401"),
                            Code = "ABDI",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Abdi İbrahim",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444402"),
                            Code = "BILIM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bilim İlaç",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Code = "EBR-MIG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("d4444444-4444-4444-4444-444444444401"),
                            Description = "Elektronik Batch Record geçiş projesi.",
                            Name = "EBR Migration",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Code = "MES-UPG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("d4444444-4444-4444-4444-444444444402"),
                            Description = "MES sürüm yükseltme projesi.",
                            Name = "MES Upgrade",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Releases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07777777-7777-7777-7777-777777777701"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b2222222-2222-2222-2222-222222222205"),
                            Description = "EBR Migration üretim yayını.",
                            EnvironmentId = new Guid("f6666666-6666-6666-6666-666666666604"),
                            Name = "REL-2026-001",
                            PlannedDate = new DateTime(2026, 7, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555501"),
                            Status = "Planned",
                            Version = "v1.0"
                        },
                        new
                        {
                            Id = new Guid("07777777-7777-7777-7777-777777777702"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("b2222222-2222-2222-2222-222222222201"),
                            Description = "MES Upgrade UAT taslak yayını.",
                            EnvironmentId = new Guid("f6666666-6666-6666-6666-666666666613"),
                            Name = "REL-2026-002",
                            PlannedDate = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("e5555555-5555-5555-5555-555555555502"),
                            Status = "Draft",
                            Version = "v0.9"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111101"),
                            Description = "Değişiklik/sürüm talebi oluşturan kullanıcı.",
                            Name = "Requester"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111102"),
                            Description = "Teknik tasarım ve mimari değerlendirme yapan kullanıcı.",
                            Name = "Architect"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111103"),
                            Description = "Onaylanan değişiklikleri yürüten kullanıcı.",
                            Name = "Executor"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111104"),
                            Description = "Doğrulama ve kalite kontrol yapan kullanıcı.",
                            Name = "QA"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111105"),
                            Description = "Sistem yöneticisi — tüm yetkiler.",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("AppUserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333301"),
                            AppUserId = new Guid("b2222222-2222-2222-2222-222222222201"),
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333302"),
                            AppUserId = new Guid("b2222222-2222-2222-2222-222222222202"),
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333303"),
                            AppUserId = new Guid("b2222222-2222-2222-2222-222222222203"),
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111103")
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333304"),
                            AppUserId = new Guid("b2222222-2222-2222-2222-222222222204"),
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111104")
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333305"),
                            AppUserId = new Guid("b2222222-2222-2222-2222-222222222205"),
                            RoleId = new Guid("a1111111-1111-1111-1111-111111111105")
                        });
                });

            modelBuilder.Entity("Gms.Api.Domain.AppEnvironment", b =>
                {
                    b.HasOne("Gms.Api.Domain.Project", "Project")
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gms.Api.Domain.Project", b =>
                {
                    b.HasOne("Gms.Api.Domain.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Gms.Api.Domain.Release", b =>
                {
                    b.HasOne("Gms.Api.Domain.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gms.Api.Domain.AppEnvironment", "Environment")
                        .WithMany("Releases")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gms.Api.Domain.Project", "Project")
                        .WithMany("Releases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Environment");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gms.Api.Domain.UserRole", b =>
                {
                    b.HasOne("Gms.Api.Domain.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gms.Api.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gms.Api.Domain.AppEnvironment", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Gms.Api.Domain.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Gms.Api.Domain.Customer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Gms.Api.Domain.Project", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Gms.Api.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
